// src/app/components/notice/notice.component.ts
import { Component, EventEmitter, Output } from '@angular/core';
import { LucideAngularModule, X } from 'lucide-angular';

@Component({
  selector: 'app-notice',
  standalone: true,
  imports: [LucideAngularModule],
  templateUrl: './notice.component.html',
  styleUrl: './notice.component.scss'
})
export class NoticeComponent {
  @Output() onClose = new EventEmitter();
  readonly X = X;

  onNoticeClosed(): void {
    this.onClose.emit();
  }
}

<div class="p-6 sm:p-4 w-full sm:w-auto bg-violet-500 items-center text-white leading-none sm:rounded-full flex sm:inline-flex bg-opacity-60 backdrop-blur-lg"
    role="alert">
    <span class="w-full font-semibold mr-2 text-left flex-auto"><ng-content></ng-content></span>
    <lucide-icon [img]="X" class="opacity-75 h-4 w-4 cursor-pointer" (click)="onNoticeClosed()"></lucide-icon>
</div>

// src/lib/components/Notice.svelte
<script lang="ts">
	import { X } from 'lucide-svelte';
	import type { Snippet } from 'svelte';

	let { children, onclose } = $props<{
		children: Snippet;
		onclose: () => void;
	}>();
</script>

<div
	class="bg-opacity-60 flex w-full items-center bg-violet-500 p-6 leading-none text-white backdrop-blur-lg sm:inline-flex sm:w-auto sm:rounded-full sm:p-4"
	role="alert"
>
	<span class="mr-2 w-full flex-auto text-left font-semibold">
		{@render children()}
	</span>
	<button
		type="button"
		class="cursor-pointer opacity-75"
		onclick={onclose}
		aria-label="Close notice"
	>
		<X class="h-4 w-4" />
	</button>
</div>
